version: "3"

services:
  redis-repl-node1:
    image: redis:6.2.6
    container_name: twitter_master_redis_node
    restart: always
    # ports:
    #   - 6379:6379
    networks:
      - twitter_redis_replica_cluster
  
  redis-repl-node2:
    image: redis:6.2.6
    container_name: twitter_secondary_redis_node_01
    command: redis-server --replicaOf twitter_master_redis_node 6379
    restart: always
    depends_on:
      - redis-repl-node1
    # ports:
    #   - 6380:6379
    networks:
      - twitter_redis_replica_cluster

  redis-repl-node3:
    image: redis:6.2.6
    container_name: twitter_secondary_redis_node_02
    command: redis-server --replicaOf twitter_master_redis_node 6379
    restart: always
    depends_on:
      - redis-repl-node1
    # ports:
    #   - 6381:6379
    networks:
      - twitter_redis_replica_cluster
  
  redis-node-sentinel:
    image: redis:6.2.6
    command: redis-server /redis-sentinel/sentinel.conf --sentinel
    volumes:
      - ./configs/sentinel.conf:/redis-sentinel/sentinel.conf
    restart: always
    depends_on:
      - redis-repl-node1
    # ports:
    #   - '26379-26383:26379'
    networks:
      - twitter_redis_replica_cluster

networks:
  twitter_redis_replica_cluster:

  